version: "3.8"

services:
  main-service:
    build:
      context: .
      dockerfile: ./main/Dockerfile
    expose:
      - "3000"
    environment:
      - DATABASE_URL=postgres://postgres:159357@db:5432/hakaton_db
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main.rule=Host(`hyper-ist.mooo.com`)"
      - "traefik.http.services.main.loadbalancer.server.port=3000"
      - "traefik.http.routers.main.entrypoints=web"

  traefik:
    image: traefik:v2.5
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    external: true
