version: "3.8"
services:
    node-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "443:443"
        environment:
            - DATABASE_URL=postgres://postgres:159357@hakaton_db-postgres-db-1:5434/hakaton_db
        networks:
            - app-network
        restart: unless-stopped

networks:
    app-network:
        external: true
