version: "3.8"

services:
  main-service:
    build:
      context: .
      dockerfile: ./main/Dockerfile
    expose:
      - "3000" # Expose port 3000 for internal network access
    environment:
      - DATABASE_URL=postgres://postgres:159357@db:5432/hakaton_db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount Nginx configuration
    ports:
      - "443:443" # Expose HTTPS on host port 443 (optional, for HTTPS)
    depends_on:
      - main-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    external: true
