version: "3.8"
services:
    node-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: node-app:latest
        ports:
            - "3333:3333"
        environment:
            - DATABASE_URL=postgres://postgres:159357@postgres-db:5432/hakaton_db
        networks:
            - app-network
        restart: unless-stopped

networks:
    app-network:
        external: true
