version: "3.8"
services:
    postgres-db:
        image: postgres:17
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=159357
            - POSTGRES_DB=hakaton_db
        ports:
            - "5434:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - app-network
        restart: unless-stopped

    node-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: node-app:18
        ports:
            - "3333:3333"
        environment:
            - DATABASE_URL=postgres://postgres:159357@postgres-db:5432/hakaton_db
        networks:
            - app-network
        depends_on:
            - postgres-db
        restart: unless-stopped

volumes:
    postgres-data:

networks:
    app-network:
        driver: bridge
