version: "3.8"
services:
  nodeapp:
    build: .
    working_dir: /app
    environment:
      - DB_NAME=hakanton_db
      - DB_USER=postgre
      - DB_PASSWORD=159357
      - DB_HOST=postgres
      - DB_PORT=5434
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
